### ISSUE TITLE
Panel menu won't show up on right click if the eye click animation is active

### ISSUE THREAD

**Issue by anaximeno** [anaximeno/c-eyes#1]
This problem also happens in other conditions:
* Trying to drop apps in the panel don't work
* Trying to drag and drop an app from another workspace to another don't work

**Comment by ghost** [comment]
Sorry for pushing here, didn't want to open a new issue just for some thoughts.
The issue seems to be caused by a bad interpretation of the hover signal from the panel(s). Seems a logical assumption as most/all other applications appear to react correctly to hover and click while the 'permanent cursor locator' is visible. The missing right-click is just a consequence of this bad interpretation.

I tried to mitigate this issue by searching for a workaround through the help of the Accessibility API, but unfortunately either I'm too dense or it's just a half-assed implementation - the latter being enforced by a mail exchange between some devs accidentally found on the web.
More precisely I wanted to add a device listener for the keyboard and use a modifier key - Ctrl was my choice - in order to temporarily hide the locator image while dragging to - or right-clicking a panel. It would've worked, albeit being more of an ugly hack - but unfortunately the device listener only works with the mouse buttons, not the keyboard. Here's some quickly cropped up code that I've tried in various combinations; the `keystroke_listener` doesn't seem to work at all, while `device_event_listener` only returns mouse clicks. Maybe I did something wrong...? Maybe there are other API that could be used successfully...?

Oh and another issue to frown upon is that incidentally I found in `/run/user/1000/` almost 140 folders created by at-spi2. Seems it either never exits properly or it doesn't clean up after itself. Following some code on the web I tried to sneak an `Atspi.exit()` in the `destroy()` method/function and it got very bad: Cinnamon started trashing the HDD then froze, and that on multiple occasions. Had to kill it from tty2, losing all running GUI apps in the session. Or maybe the addition of the `exit()` triggered the issue. Couldn't find it in me to pursue that too after all the struggle. I'm already at 24 hours of non-stop keyboard banging.

The idle basically works fine but I had to butcher the code in the process. You won't like it. And it triggered yet another issue: it needs a way to detect fullscreen exclusive mode apps running and automatically disable the idle, otherwise people would see the animation on top of their presentations or movies or games or whatever they may be running in that exclusive mode. Not nice at all. That was a whole can of worms back in the Windows days, never managed to find the perfect solution even then.

Anyway, here's the listener code, maybe you can find a bug or a way to make it work.

```
constructor(...) {
		[...]
		try {
		this.modType = Atspi.ModifierType.SHIFT; // 0 | CONTROL
		this.keyEvent = Atspi.EventType.KEY_PRESSED_EVENT; // Atspi.EventType.KEY_RELEASED_EVENT
		this.syncType = Atspi.KeyListenerSyncType.SYNCHRONOUS | Atspi.KeyListenerSyncType.ALL_WINDOWS | Atspi.KeyListenerSyncType.CANCONSUME;
		this.kl = Atspi.DeviceListener.new(this.listen.bind(this));
//		this.kl.synchronous=true;
//		this.kl.preeemptive=true;
		let kl = Atspi.register_keystroke_listener(
			this.kl,
			null,
			this.modType,
			this.keyEvent,
			this.syncType)
		if (!kl)
			global.logError("can't register keystroke_listener");
		let dl = Atspi.register_device_event_listener(
			this.dl,
			this.keyEvent,
			null)
		if (!dl)
			global.logError("can't register device_event_listener");
// Mod_type: ATSPI_MODIFIER_CONTROL
// Event_type: ATSPI_KEY_PRESSED, ATSPI_KEY_RELEASED (deprecated) | ATSPI_KEY_PRESSED_EVENT, ATSPI_KEY_RELEASED_EVENT
// Sync_type: ATSPI_KEYLISTENER_SYNCHRONOUS
		global.log("this.kl=" + this.kl.toString());
		global.log("this.dl=" + this.dl.toString());
		global.log("Ctrl=" + Atspi.ModifierType.CONTROL.toString());
		global.log("Press=" + Atspi.EventType.KEY_PRESSED_EVENT.toString());
		global.log("Release=" + Atspi.EventType.KEY_RELEASED_EVENT.toString());
		global.log("Synchr=" + Atspi.KeyListenerSyncType.SYNCHRONOUS.toString());
		global.log("AllWin=" + Atspi.KeyListenerSyncType.ALL_WINDOWS.toString());
		global.log("Cons=" + Atspi.KeyListenerSyncType.CANCONSUME.toString());
		} catch(e) {global.logError("Error: " + e); }
		[...]
	}

	listen(event, data=null) {
	// params: id, hw_code, modifiers, timestamp, event_string, is_text
	global.log(event.modifiers.toString());
	global.log(event.id.toString());
	return false;
	}

	destroy() {
		[...]
		Atspi.deregister_keystroke_listener(this.kl, null, this.modType, this.keyEvent);
		Atspi.deregister_device_event_listener(this.dl, null);
		[...]
	}

```

**Comment by anaximeno** [comment]
> The issue seems to be caused by a bad interpretation of the hover signal from the panel(s). Seems a logical assumption as most/all other applications appear to react correctly to hover and click while the 'permanent cursor locator' is visible. The missing right-click is just a consequence of this bad interpretation.

Yeah, I thought it was something like that.

> I tried to mitigate this issue by searching for a workaround through the help of the Accessibility API, but unfortunately either I'm too dense or it's just a half-assed implementation - the latter being enforced by a mail exchange between some devs accidentally found on the web.
More precisely I wanted to add a device listener for the keyboard and use a modifier key - Ctrl was my choice - in order to temporarily hide the locator image while dragging to - or right-clicking a panel. It would've worked, albeit being more of an ugly hack - but unfortunately the device listener only works with the mouse buttons, not the keyboard. Here's some quickly cropped up code that I've tried in various combinations; the keystroke_listener doesn't seem to work at all, while device_event_listener only returns mouse clicks. Maybe I did something wrong...? Maybe there are other API that could be used successfully...?

Keyboard events can be handled with signals if I am not wrong, the cinnamon extension gTile has some keyboard events it may be a good example.

> Oh and another issue to frown upon is that incidentally I found in /run/user/1000/ almost 140 folders created by at-spi2. Seems it either never exits properly or it doesn't clean up after itself. Following some code on the web I tried to sneak an Atspi.exit() in the destroy() method/function and it got very bad: Cinnamon started trashing the HDD then froze, and that on multiple occasions. Had to kill it from tty2, losing all running GUI apps in the session.

I am studying not adding the Atspi.init() on the constructor of the class. For what I tested untill now, it seems to work well even without that init, but I have to analyse if there are any side effects on that change.

**Comment by ghost** [comment]
Haven't looked at gTile ever. It's possible it just has some hotkeys registered, which would not be useful for the issue at hand. I do have some sort of key listener in my _betterlockPlus_ applet, if anything I could try the same approach here.

In the mean time I had another idea which seems to be stuck as well: get the hovered window ID, compare it to a list of active panel IDs, and if matches automatically disable the 'circle' (pointer tracker).
That would be much more friendly as it wouldn't require manual intervention (pressing of a modifier key). I'm still searching for the appropriate APIs.

In the version I've been working on offline I use Atspi for mouse movement too besides the clicks. It does introduce a slightly unwanted effect: currently running tween cannot be interrupted by mouse move or click. Maybe my code is faulty. Will keep looking into this as well.

Right now I'm in the process of reorganizing settings and renaming some variables which can always slip bugs in.
Oh and I added a tooltip. Hate applets that don't display a tooltip. 😸

**Comment by ghost** [comment]
Might've found a workable solution albeit not the perfect one.
Make sure you backup your current settings file before installing this version as it will break it.
- added 'idle tracker' mode with automatic detection of fullscreen application
- added rich tooltip
- restored 'pointer tracker' mode
- implemented workaround for panel hover bug by temporarily keeping **Ctrl** pressed
- implemented quick toggling of main functions (click/pointer/idle tracker) through Shift/+Ctrl+click on panel icon
(plus instant idle toggle through middle-click)

This version is for Cinnamon 4.2 - 5.2 only. If you find it acceptable you may adapt it to 5.4+. It shouldn't be much work, apart from replacing _Tweener_ with _easing_. Sorry for the code butchering. 😊

[4.2v1.9.7.zip](https://github.com/anaximeno/c-eyes/files/10699172/4.2v1.9.7.zip)

**Comment by anaximeno** [comment]
> Might've found a workable solution albeit not the perfect one. Make sure you backup your current settings file before installing this version as it will break it.
> 
> * added 'idle tracker' mode with automatic detection of fullscreen application
> * added rich tooltip
> * restored 'pointer tracker' mode
> * implemented workaround for panel hover bug by temporarily keeping **Ctrl** pressed
> * implemented quick toggling of main functions (click/pointer/idle tracker) through Shift/+Ctrl+click on panel icon
>   (plus instant idle toggle through middle-click)
> 
> This version is for Cinnamon 4.2 - 5.2 only. If you find it acceptable you may adapt it to 5.4+. It shouldn't be much work, apart from replacing _Tweener_ with _easing_. Sorry for the code butchering. blush
> 
> [4.2v1.9.7.zip](https://github.com/anaximeno/c-eyes/files/10699172/4.2v1.9.7.zip)

Sure, I'll take a look into it.

**Comment by ghost** [comment]
Fixed some things in icon click logic, updated the tooltip info, added translation capability (no .pot file created), added startup mode selection.
Haven't checked your latest commit [here](https://github.com/anaximeno/c-eyes/commit/130439ac24af232496e0ca64d60a3cb02b688dce) yet, been working on the offline code. Hopefully there are no (major) bugs left.

Here's what I got:
[4.2v1.9.8.zip](https://github.com/anaximeno/c-eyes/files/10712977/4.2v1.9.8.zip)

**Comment by anaximeno** [comment]
Hi @Drugwash2.

I've tested some of the changes you've made on a VM and they worked well. I might port some of them to the 5.4+ versions as well. But, before adding them, I am planning to make some refactoring to allow to easily add new eye modes (styles) and click animations.

Even though I've initialized the refactor, it might take some time due to my compromises.

**Comment by ghost** [comment]
Ah, I've been meaning to post an updated mod yesterday but it was too late, was tired.
I had already added the changes to the 5.4 version too keeping the `ease` as effect, as opposed to `tweener` in the 4.2 version. It worked well on a short test under a 21.1 VM.

Here it is, hoping it would relieve some burden: 
[c-eyes@anaximeno 1.9.9 MOD.zip](https://github.com/anaximeno/c-eyes/files/10757264/c-eyes%40anaximeno.1.9.9.MOD.zip)

By the way, would you happen to know a way to get notified through signals on global keypresses? I failed to find any. It's something very close to a keylogger so it's understandable to be somewhat hidden, but here it would only require the knowledge of **some** key pressed - not the actual keys. It would be useful to complete the idle detection, because currently only mouse movement counts toward idle while key presses are ignored, and that could become uncomfortable while typing some long text in a document or whatever and having the idle tracker constantly flashing on the screen. Of course it can easily be turned off but it would be more professional and complete to have full mouse and keyboard activity detection.
And before you say it: no, system idle/screensaver timer won't work as certain applications are able to reset the system idle timer, and using yet another timer here to poll some system file or whatever would not be an elegant solution anyway.

**Comment by anaximeno** [comment]
> Here it is, hoping it would relieve some burden: [c-eyes@anaximeno 1.9.9 MOD.zip](https://github.com/anaximeno/c-eyes/files/10757264/c-eyes%40anaximeno.1.9.9.MOD.zip)

Thanks, it helped!

> By the way, would you happen to know a way to get notified through signals on global keypresses? I failed to find any. It's something very close to a keylogger so it's understandable to be somewhat hidden, but here it would only require the knowledge of **some** key pressed - not the actual keys. It would be useful to complete the idle detection, because currently only mouse movement counts toward idle while key presses are ignored, and that could become uncomfortable while typing some long text in a document or whatever and having the idle tracker constantly flashing on the screen. Of course it can easily be turned off but it would be more professional and complete to have full mouse and keyboard activity detection. And before you say it: no, system idle/screensaver timer won't work as certain applications are able to reset the system idle timer, and using yet another timer here to poll some system file or whatever would not be an elegant solution anyway.

I've been analysing the cinnamon codebase, and I believe the signal for keypresses is **key-press-event**.

![Captura de ecrã de 2023-02-21 01-41-27](https://user-images.githubusercontent.com/63073056/221438673-e60f4697-eacc-4e9f-be49-9c2a681f3985.png)

**Comment by anaximeno** [comment]
I decided not to implement some of the features you added to your mod yet. I will implement some of them for a 2.0 version like the idle monitor and the permanent circle image. I saw that you've been using the atspi event listener to listen to the mouse events and draw the eye when the position changed, I also thought about that but didn't implement it at the time because I still want the user to define the minimum interval between repaints because it helps to reduce the resource usage while drawing the eye on the panel. That said, I still want to implement with the event listener on the atspi because it removes the need to have a callback being called even when not necessary, so I will implement a solution that should involve both the atspi listener to draw the eye and a minimum repaint interval.

Here's the version I am planning to send as a first update to the applet [c-eyes.zip](https://github.com/anaximeno/c-eyes/files/10834824/c-eyes.zip)

**Comment by ghost** [comment]
> Thanks, it helped!

You're welcome. :thumbsup:

> I believe the signal for keypresses is **key-press-event**.

Have you checked if the signal is received globally from **any** window, Terminal and Desktop included?

> I decided not to implement some of the features you added to your mod yet.

No worries - it's your applet, you're the boss. I just came up with some gimmicks I had in mind for a long time (and which worked in Windows through AHK). 😄 It's best to ponder over the available options and choose the most appropriate. Code's there, and your idea is good. :wink:

> Here's the version I am planning to send as a first update

Thanks, I'll have a look when time'll be on my side; right now struggling with some kinks and coffee doesn't help much anymore. :tired_face:
